set tabstop=4
set shiftwidth=4
set cindent

syntax on
highlight Comment ctermfg=green

" --- OmniCppComplete ---
" -- required --
set nocp " non vi compatible mode
filetype plugin on " enable plugins

" -- optional --
" auto close options when exiting insert mode
autocmd InsertLeave * if pumvisible() == 0|pclose|endif
set completeopt=menu,menuone

" -- configs --
let OmniCpp_MayCompleteDot = 1 " autocomplete with .
let OmniCpp_MayCompleteArrow = 1 " autocomplete with ->
let OmniCpp_MayCompleteScope = 1 " autocomplete with ::
let OmniCpp_SelectFirstItem = 2 " select first item (but don't insert)
let OmniCpp_NamespaceSearch = 2 " search namespaces in this and included files
let OmniCpp_ShowPrototypeInAbbr = 1 " show function prototype (i.e. parameters) in popup window

" -- ctags --
" Map <ctrl>+F12 to generate ctags for current folder
map <C-F12> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR><CR>
" Add current directory's generated tags file to available tags
set tags+=./tag
" Add Standard Template Library to the available tags
set tags+=~/.vim/tags/stlTags
" Add OpenGL to the tags
set tags+=~/.vim/tags/glTags
set tags+=~/.vim/tags/glewTags
" Add SDL and SFML to the tags
set tags+=~/.vim/tags/SDLTags
set tags+=~/.vim/tags/SFMLTags

" Map autocomplete to CTRL + Space
if has("gui-running")
	" ctrl + space seems to work under gVim on both Linuc and Windows
	inoremap <C-Space> <C-n>
else " If not using gui
	if has("unix")
		inoremap <Nul> <C-n>
	else
		" Add keyboard binding for other operating systems. It's different,
		" probably
		inoremap <Nul> <C-n>
	endif
endif
